@startuml
'https://plantuml.com/class-diagram
skinparam componentStyle rectangle

Listing "1" -- "0..1" Auction : > can be
Listing "1   " -- "0..1   " DirectSale : > can be
Listing "1..*" -- "       1" Seller : > created by
Listing "1" -- "1" Item : > lists

note as L
    Represents a sale ad (direct sale or auction)
    end note

Listing -> L

Item "*" -- "1" BibliographicalData : > has
note as N
    Catalog
    Represents the conceptual idea of Magazine or Book.
    end note

BibliographicalData --> N

note as S
    Stock
    Contains real attributes such as weight, condition and real photos of the item
    end note

Item - S

Book "1" -- "1" Item : > is an
Magazine "1" -- "1" Item : > is an

Buyer "1  " --- "1..*" DirectSale : > makes
Cart "1" -- "0..1" Transaction : > can turn into
DirectSale "*" --> "1" Cart : > listed in

Auction "1" -- "*" Bid : > has
Auction "1" -- "1" Transaction : > becomes
Bid "*" -- "1" Bidder : > made by

Bidder -- User : > is

Seller -- User : > is
Buyer - User : > is

component Listing{
}
component Item {
}
component BibliographicalData {
}
component Seller {
}
component Buyer {
}
component Bidder {
}
component Bid {
}
component Cart {
}
component DirectSale {
}
component Transaction {
}
component Book{
}
component Magazine{
}
component Auction {
}
component User {
}

@enduml