@startuml Doo
'https://plantuml.com/class-diagram

/' ========= '/
Listing --- Auction
Listing ..> SaleType

/' ========= '/
Book --- Listing
Magazine --- Listing

/' ========= '/
BibliographicalData ..> Language 
BibliographicalData ..> Genre 
BibliographicalData -- Author
BibliographicalData -- Publisher
BibliographicalData -- Code



/' ========= '/
Item -- BibliographicalData
Item -- Picture
Item -- Dimension
Item ..> TypeOfBinding
Item ..> Condition


/' ========= '/
Cart "1" o-- "0..*" Listing
Cart "1" --> "1" User : buyer

/' ========= '/
Transaction --> Listing
Transaction --> User : seller
Transaction --> User : buyer

/' ========= '/
User --> Profile



/' ========= '/
Contact "1" *-- "1" Email


Address ..> Country

/' ========= '/
Publisher -- Address
Publisher -- Contact


class Book {
    - item:Item
    - listing:Listing
}

class Magazine {
    - item:Item
    - listing:Listing
}

class User {
    - userName:String
    - contact:Contact
    - profile:Profile
}

class Profile {
    name:String
    country:Country
    birthday:LocalDate
}


class Author {
    - profile:Profile
}


class Item {
    -itemDescription:BibliographicalData
    - condition:Condition
    - weight:int
    - pictures[]: Picture
    - dimensions: Dimension
    - typeOfBinding:TypeOfBinding
    - edition:String

}

class BibliographicalData {
    - title1:Title
    - author[]:Author
    - language:Language
    - code:Code
    - publisher:Publisher
    - publicationDate:LocalDateTime
    - genre[]:Genre
    - numberOfPages:int
    - chunksOfText: String

}

class Listing {
    /'- item:Item'/
    - price:double
    - shortDescription:String
    - listingTitle:String
    - saleType:SaleType
    - seller:User
}



class Cart {
    - itemsList[]:Listing
    - buyer:User
}


class Auction {
    - auctionedItem:Listing
    - buyOutPrice:double
    - initialDate:LocalDateTime
    - finalDate:LocalDateTime
    - initialPrice:double
    - bidHistory[]:Bid
    
    /' currentBidder:User... sim ou não????'/
}

class Bid {
    - bidder:User
    - value:double
}

class Transaction {
    - sellers:List<User>
    - buyer:User
    - :

}


class LogisticsServices {
}

class SupportService {
}

class Community{
}

class Dimension {
    - length:int
    - height:int
    - width:int
}

enum Language {
    PORTUGUESE
    ENGLISH
    SPANISH
}

class Code {
    - isbn10:String
    - isbn13:String
    - issn:String
}

class Publisher {
    - name:String
    - vatNumber:String
    - address:Address
    - contact:Contact
}

class Address {
    - street:String
    - number:String
    - zipCode:String
    - country:Country
}

enum Country {
    PORTUGAL
    SPAIN
    FRANCE
    GERMANY
}

class Contact {
    - phoneNum:String
    - extension:Extension
    - email:Email /'review'/
}

class Email {
    - userName:String
    - domain:String
}

enum Genre {
    ADVENTURE
    ROMANCE
    FICTION
}

enum TypeOfBinding {
    HARDBACK
    PAPERBACK

}

enum SaleType {
    DIRECT_SALE
    AUCTION
}

enum Extension {

}

enum Condition {
    NEW
    LIKE_NEW
    VERY_GOOD
    GOOD
    ACCEPTABLE
}

@enduml