@startuml
'https://plantuml.com/class-diagram

title Mite lovers - AOO Level 1
skinparam title {
  FontSize 24
}


skinparam ArrowColor #333
skinparam ClassBackgroundColor #DDDDFF
skinparam ClassBorderColor #0000FF
skinparam Shadowing false
skinparam componentStyle rectangle
skinparam componentBorderColor DarkBlue
skinparam component<<highlight>> {
    BackgroundColor LightBlue
}
skinparam legend {
  BackgroundColor LightBlue
  FontSize 14
}

legend right
 Suggestion to discuss
end legend


Listing "1" -- "              0..1" Auction : > can be an
Listing "  1   " --- "  0..1 " DirectSale : > can be a
Listing "1..*" -- "       1" Seller : > is created by
Listing "1" -- "1" Item : > announces

note as L
    Represents a sale ad (direct sale or auction)
    end note

Listing -> L

Book "0..1" -- "1" Item : > is a
Magazine "0..1" -- "1" Item : > is a
/'Item "1" - "0..1" Book : < is an
Item "1" - "0..1" Magazine : < is an'/
Item "*" -- "1" BibliographicalData : > has

note as N
    Catalog
    Refers to the bibliographical information of either a Magazine or
    a Book (for example, title, authors, date of publication).
    end note

BibliographicalData --> N

note as S
    Stock
    Contains physical attributes such
    as weight, condition and real photos of the item
    end note

Item - S




Buyer "1  " --- "  1..* " DirectSale : > buys through
Cart "1" --- "0..1    " Transaction : > can result  in
DirectSale "        *" --- "1 " Cart : > added to


Auction "   1  " -- "*" Bid : > may have
Auction "0..1" -- "0..1" Transaction : > can result in
Bid "*" -- "                  1" Bidder : > offered by

Transaction "1" -- "1 " LogisticsServices : > shipped by
Transaction "1" -- "0..1" SupportService : > managed by

Listing "  1 " --------- "0..1" SupportService : > is regulated by

/'Community "1  " --- "1..*" User : > is composed of'/
User -- Community
Bidder "0..1" -- "1" User : > is a

Seller "0..1 " -- "1" User : > is a
Buyer "0..1" - "1" User : > is a

User "1" -- "*" SupportService : > can request

component Listing {
}
component Item {
}
component BibliographicalData {
}
component Seller {
}
component Buyer {
}
component Bidder {
}
component Bid {
}
component Cart {
}
component DirectSale {
}
component Transaction {
}
component LogisticsServices #LightBlue {
}
component SupportService #LightBlue{
}
component Community #LightBlue {
}
component Book{
}
component Magazine{
}
component Auction {
}
component User {
}




@enduml